import Link from "next/link";
import { divisions } from "../data/divisionContent";
import { mainLogo } from "../data/companyIdentity";
import type { SiteContent } from "../data/siteContent";
import type { RequestRecord } from "../data/requests";

export default function AdminHome({ content, requests }: { content: SiteContent; requests: RequestRecord[] }) {
  const active = requests.filter(r=>!r.archived);
  const banners = content.promotions.slice(0,3);
  return <div className="admin-home"><header><Link href="/admin" className="admin-home-brand"><img src={mainLogo} alt="MBI Laser Cutting"/>MAHAMERU <small>CONTENT STUDIO</small></Link><div><Link href="/">Lihat website ↗</Link><form action="/api/admin/logout" method="post"><button type="submit">Keluar</button></form></div></header><main>
    <p className="industrial-eyebrow">AGENDA & INFORMASI BERANDA</p><h1>Hari ini di<br /><em>Mahameru.</em></h1><p className="admin-home-intro">Atur kegiatan, promo, artikel, dan video company profile. Lanjutkan ke ruang kerja untuk menindaklanjuti pelanggan divisi Anda.</p>
    <section className="admin-event-grid" aria-label="Banner kegiatan">{banners.map(b=><Link key={b.id} href="/admin/promosi"><img src={b.image} alt=""/><div><small>{b.published?"Terbit":"Draf"} · {b.label}</small><h2>{b.title}</h2><span>Edit banner ↗</span></div></Link>)}<Link href="/admin/hero" className="admin-hero-tile"><small>GAMBAR & VIDEO COMPANY PROFILE</small><h2>Hero beranda.</h2><p>Unggah video, pilih poster, atur urutan dan tombol.</p><span>Kelola hero ↗</span></Link></section>
    <div className="admin-home-metrics"><div><small>PERMINTAAN AKTIF</small><strong>{active.length}</strong></div><div><small>PERLU TINDAK LANJUT</small><strong>{active.filter(r=>r.status==="Baru"||r.status==="Review kebutuhan").length}</strong></div><div><small>DIVISI</small><strong>05</strong></div><div><small>KONTAK ADMIN</small><strong>{content.contacts.filter(c=>c.published).length}</strong></div></div>
    <div className="admin-home-sections">{[{href:"/admin/galeri",label:"GALERI & PROYEK",title:"Satu proyek, banyak foto.",text:"Tambah album, unggah foto sekaligus, pilih sampul, susun urutan, dan terbitkan."},{href:"/admin/produk",label:"KATALOG & STOK",title:"Produk per divisi.",text:"Pilih produk tiap divisi, isi sisa stok dan satuan, lalu konfirmasikan ketersediaan."},{href:"/admin/permintaan",label:"SALES DESK",title:"Permintaan & invoice.",text:"Catat kebutuhan, ubah progres, arsipkan, dan unduh PDF permintaan atau draf invoice."},{href:"/admin/konten",label:"KONTAK & ULASAN",title:"Tim dan pengalaman pelanggan.",text:"Kelola nomor WhatsApp tiap divisi dan ulasan Google Maps."},{href:"/admin/sosial",label:"SOSIAL MEDIA",title:"Akun & video pilihan.",text:"Kelola Instagram, TikTok, YouTube, serta video yang dapat diputar di website."},{href:"/admin/promosi",label:"BANNER & KEGIATAN",title:"Promo dan agenda.",text:"Unggah banner, isi detail, atur tanggal, dan terbitkan."},{href:"/admin/artikel",label:"ARTIKEL & PANDUAN",title:"Pengetahuan untuk pelanggan.",text:"Tulis dengan editor visual, unggah gambar, simpan draf, pratinjau, dan terbitkan artikel."}].map(item=><Link key={item.href} href={item.href}><span>{item.label}</span><h2>{item.title}</h2><p>{item.text}</p><b>Buka ruang kerja ↗</b></Link>)}</div>
    <section className="admin-home-recent"><h2>Permintaan terbaru.</h2>{active.slice(0,5).map(r=><Link key={r.id} href="/admin/permintaan"><span>{r.id}</span><strong>{r.name}</strong><small>{divisions.find(d=>d.slug===r.businessUnitSlug)?.label} / {r.status}</small></Link>)}{!active.length&&<p>Belum ada permintaan untuk akun ini.</p>}</section>
    <nav className="admin-division-directory" aria-label="Website divisi"><h2>Lima website divisi</h2>{divisions.map(d=><Link href={`/unit/${d.slug}`} key={d.slug}>{d.name} ↗</Link>)}<p>Permintaan dipisahkan menurut divisi akun. Konten company profile dikelola bersama.</p></nav>
  </main></div>;
}
