import Link from "next/link";
import { divisions } from "../data/divisionContent";
import type { SiteContent } from "../data/siteContent";
import type { RequestRecord } from "../data/requests";

export default function AdminHome({ content, requests }: { content: SiteContent; requests: RequestRecord[] }) {
  const active=requests.filter(r=>!r.archived);
  return <div className="admin-home"><header><Link href="/admin" className="admin-home-brand"><img src="/mbi-mark.svg" alt="" />MAHAMERU BAJA <small>CONTENT STUDIO</small></Link><div><Link href="/">Lihat website ↗</Link><form action="/api/admin/logout" method="post"><button type="submit">Keluar</button></form></div></header><main><p className="industrial-eyebrow">PORTAL ADMIN / TERSIMPAN DI SERVER</p><h1>Kelola konten.<br /><em>Tindak lanjuti kebutuhan.</em></h1><p className="admin-home-intro">Permintaan pelanggan, ulasan, kontak, dan sosial media berada dalam satu portal. Pilih area yang akan dikerjakan.</p><div className="admin-home-metrics"><div><small>PERMINTAAN AKTIF</small><strong>{active.length}</strong></div><div><small>MENUNGGU TINDAK LANJUT</small><strong>{active.filter(r=>r.status==="Baru"||r.status==="Review kebutuhan").length}</strong></div><div><small>ULASAN TERBIT</small><strong>{content.reviews.filter(r=>r.published).length}</strong></div><div><small>KONTAK TERBIT</small><strong>{content.contacts.filter(c=>c.published).length}</strong></div></div><div className="admin-home-sections"><Link href="/admin/permintaan"><span>01 / SALES DESK</span><h2>Permintaan pelanggan.</h2><p>Catat, ubah status, lengkapi daftar material, buat PDF, dan tindak lanjuti WhatsApp.</p><b>Masuk ruang kerja ↗</b></Link><Link href="/admin/konten"><span>02 / KONTEN PUBLIK</span><h2>Kontak & ulasan.</h2><p>Atur PIC tiap divisi, kontak, rating, dan ulasan asli yang tampil di beranda.</p><b>Kelola konten ↗</b></Link><Link href="/admin/sosial"><span>03 / KANAL</span><h2>Sosial media.</h2><p>Kelola akun serta unggahan yang tampil di halaman sosial dan beranda.</p><b>Kelola kanal ↗</b></Link></div><section className="admin-home-recent"><div><p className="industrial-eyebrow">AKTIVITAS TERBARU</p><h2>Permintaan masuk.</h2></div>{active.slice(0,5).map(r=><Link key={r.id} href="/admin/permintaan"><span>{r.id}</span><strong>{r.name}</strong><small>{divisions.find(d=>d.slug===r.businessUnitSlug)?.label} / {r.status}</small></Link>)}{active.length===0&&<p>Belum ada permintaan. Form publik akan mencatatnya di sini.</p>}</section></main></div>;
}
