"use client";
import { useState } from "react";
import { invoiceSchema, type Invoice, type RequestRecord } from "../data/requests";
import { jakartaDate } from "../lib/jakartaDate";
export default function InvoiceEditor({ record, onSaved }: { record: RequestRecord; onSaved: (record: RequestRecord)=>void }) {
  const [invoice,setInvoice]=useState<Invoice>(record.invoice||{number:`INV-${record.id}`,issuedAt:jakartaDate(),dueAt:"",notes:"Harga, pajak, dan ketentuan pembayaran menunggu persetujuan tim.",lines:record.items.length?record.items.map(item=>({description:`${item.productName}${item.specification?` / ${item.specification}`:""}`,quantity:item.quantity||1,unit:item.unit||"",price:0})):[{description:"",quantity:1,unit:"",price:0}]});
  const [busy,setBusy]=useState(false),[message,setMessage]=useState("");
  async function save(){setBusy(true);setMessage("");try{const parsed=invoiceSchema.parse(invoice);const response=await fetch(`/api/admin/requests?id=${record.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({revision:record.revision,invoice:parsed})});const saved=await response.json();if(!response.ok)throw new Error(saved.message);onSaved(saved);setMessage("Draf invoice tersimpan.");}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
  async function download(){setBusy(true);setMessage("");try{const parsed=invoiceSchema.parse(invoice);const {invoicePdf}=await import("../lib/invoicePdf");const bytes=await invoicePdf(record,parsed);const url=URL.createObjectURL(new Blob([bytes.slice().buffer as ArrayBuffer],{type:"application/pdf"}));const link=document.createElement("a");link.href=url;link.download=`${record.id}-draft-invoice.pdf`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
  return <section className="invoice-editor"><h3>Draf invoice</h3><p>Isi harga yang telah diperiksa tim. Template final, pajak, rekening dan syarat pembayaran belum diberikan klien; output tetap ditandai draf.</p><div className="requests-fields">{(["number","issuedAt","dueAt"] as const).map(key=><label key={key}>{{number:"Nomor invoice",issuedAt:"Tanggal",dueAt:"Jatuh tempo"}[key]}<input type={key==="number"?"text":"date"} value={invoice[key]} onChange={e=>setInvoice(c=>({...c,[key]:e.target.value}))}/></label>)}</div>{invoice.lines.map((line,index)=><div className="invoice-line" key={index}><label>Uraian<input value={line.description} onChange={e=>setInvoice(c=>({...c,lines:c.lines.map((l,i)=>i===index?{...l,description:e.target.value}:l)}))}/></label>{(["quantity","price"] as const).map(key=><label key={key}>{key==="price"?"Harga satuan (Rp)":"Jumlah"}<input type="number" min={key==="price"?0:.001} step="any" value={line[key]} onChange={e=>setInvoice(c=>({...c,lines:c.lines.map((l,i)=>i===index?{...l,[key]:Number(e.target.value)}:l)}))}/></label>)}<label>Satuan<input value={line.unit} onChange={e=>setInvoice(c=>({...c,lines:c.lines.map((l,i)=>i===index?{...l,unit:e.target.value}:l)}))}/></label><button disabled={invoice.lines.length===1} onClick={()=>setInvoice(c=>({...c,lines:c.lines.filter((_,i)=>i!==index)}))}>Hapus</button></div>)}<button disabled={invoice.lines.length>=40} onClick={()=>setInvoice(c=>({...c,lines:[...c.lines,{description:"",quantity:1,unit:"",price:0}]}))}>+ Item invoice</button><label className="requests-wide">Catatan<textarea value={invoice.notes} onChange={e=>setInvoice(c=>({...c,notes:e.target.value}))}/></label><strong>Total: {new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR"}).format(invoice.lines.reduce((sum,l)=>sum+l.quantity*l.price,0))}</strong><div className="requests-actions"><button disabled={busy} onClick={save}>Simpan draf</button><button disabled={busy} onClick={download}>Unduh PDF invoice</button></div>{message&&<p role="status">{message}</p>}</section>;
}
